# Generated by Django 2.2 on 2019-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
