# Generated by Django 2.2 on 2019-04-28 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads_page', '0002_postfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='file_key',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comments',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
